function inside = pointInCube(minVerts, maxVerts, point)
inside = false;
%need to round for the case of point is one of the min or max vertices
if round(minVerts(1),2) <= round(point(1),2)... 
    && round(point(1),2) <= round(maxVerts(1),2)...
    && round(minVerts(2),2) <= round(point(2),2)...
    && round(point(2),2) <= round(maxVerts(2),2)...
    && round(minVerts(3),2) <= round(point(3),2)...
    && round(point(3),2) <= round(maxVerts(3),2)
    inside = true;
end
end